version: '3.9'

services:
  app:
    image: ghcr.io/sceuick/agnaistic:latest
    networks:
      storage_swarm:
        aliases:
          - agnaistic
    deploy:
      replicas: 1
    ports: 
      - '3001:3001'
    volumes:
      - agn-data:/app/db
      - agn-assets:/app/dist/assets
    environment:
      DB_NAME: agnai
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

networks:
  storage_swarm:
    external: true

secrets:
  jwt_secret:
    external: true

volumes:
  agn-data:
  agn-assets: