version: '3.9'

services:
  app:
    image: ghcr.io/luminai-companion/agnaistic:latest
    networks:
      storage_swarm:
        aliases:
          - agnaistic
    deploy:
      replicas: 2
    ports:
      - '3001:3001'
    volumes:
      - agn-data:/app/db
      - agn-assets:/app/dist/assets
    environment:
      LOG_LEVEL: info
      DB_NAME: agnai
      DB_HOST: mongodb
      DB_PORT: 27017
      NODE_ENV: production
      JWT_SECRET: /run/secrets/jwt_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HORDE_WAIT_SECS: 150
      CHAI_URL: /run/secrets/chai_url
      CHAI_UID: /run/secrets/chai_uid
      CHAI_KEY: /run/secrets/chai_token
      ADAPTERS: horde,novel,kobold,openai,scale,claude
      AWS_ACCESS_KEY_ID: /run/secrets/aws_id
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws_secret
      BUCKET_NAME: /run/secrets/bucket_name
      BUCKET_ENDPOINT: /run/secrets/bucket_endpoint
    secrets:
      - jwt_secret
      - chai_url
      - chai_uid
      - chai_token
      - aws_id
      - aws_secret
      - bucket_name
      - bucket_endpoint

networks:
  storage_swarm:
    external: true

secrets:
  jwt_secret:
    external: true
  chai_url:
    external: true
  chai_uid:
    external: true
  chai_token:
    external: true
  aws_id:
    external: true
  aws_secret:
    external: true
  bucket_name:
    external: true
  bucket_endpoint:
    external: true

volumes:
  agn-data:
  agn-assets:
